/*
 * generated by Xtext 2.34.0
 */
package org.xtext.example.ims.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.example.ims.IMSRuntimeModule;
import org.xtext.example.ims.IMSStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class IMSIdeSetup extends IMSStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new IMSRuntimeModule(), new IMSIdeModule()));
	}
	
}
