/*
 * generated by Xtext 2.34.0
 */
package org.xtext.example.ims.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.example.ims.ui.internal.ImsActivator;

public class IMSUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return ImsActivator.getInstance().getInjector("org.xtext.example.ims.IMS");
	}

}
