/*
 * generated by Xtext 2.34.0
 */
package org.xtext.example.ims.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import org.xtext.example.ims.ui.internal.ImsActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class IMSExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(ImsActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		ImsActivator activator = ImsActivator.getInstance();
		return activator != null ? activator.getInjector(ImsActivator.ORG_XTEXT_EXAMPLE_IMS_IMS) : null;
	}

}
