/**
 * generated by Xtext 2.34.0
 */
package org.xtext.example.ims.iMS.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.xtext.example.ims.iMS.CompoundExpression;
import org.xtext.example.ims.iMS.Expression;
import org.xtext.example.ims.iMS.IMSPackage;
import org.xtext.example.ims.iMS.Operator;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Compound Expression</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.ims.iMS.impl.CompoundExpressionImpl#getLHS <em>LHS</em>}</li>
 *   <li>{@link org.xtext.example.ims.iMS.impl.CompoundExpressionImpl#getOperator <em>Operator</em>}</li>
 *   <li>{@link org.xtext.example.ims.iMS.impl.CompoundExpressionImpl#getRHS <em>RHS</em>}</li>
 * </ul>
 *
 * @generated
 */
public class CompoundExpressionImpl extends ExpressionImpl implements CompoundExpression
{
  /**
   * The cached value of the '{@link #getLHS() <em>LHS</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLHS()
   * @generated
   * @ordered
   */
  protected Expression lhs;

  /**
   * The default value of the '{@link #getOperator() <em>Operator</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOperator()
   * @generated
   * @ordered
   */
  protected static final Operator OPERATOR_EDEFAULT = Operator.AND;

  /**
   * The cached value of the '{@link #getOperator() <em>Operator</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOperator()
   * @generated
   * @ordered
   */
  protected Operator operator = OPERATOR_EDEFAULT;

  /**
   * The cached value of the '{@link #getRHS() <em>RHS</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRHS()
   * @generated
   * @ordered
   */
  protected Expression rhs;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected CompoundExpressionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return IMSPackage.Literals.COMPOUND_EXPRESSION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Expression getLHS()
  {
    return lhs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetLHS(Expression newLHS, NotificationChain msgs)
  {
    Expression oldLHS = lhs;
    lhs = newLHS;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, IMSPackage.COMPOUND_EXPRESSION__LHS, oldLHS, newLHS);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setLHS(Expression newLHS)
  {
    if (newLHS != lhs)
    {
      NotificationChain msgs = null;
      if (lhs != null)
        msgs = ((InternalEObject)lhs).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - IMSPackage.COMPOUND_EXPRESSION__LHS, null, msgs);
      if (newLHS != null)
        msgs = ((InternalEObject)newLHS).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - IMSPackage.COMPOUND_EXPRESSION__LHS, null, msgs);
      msgs = basicSetLHS(newLHS, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, IMSPackage.COMPOUND_EXPRESSION__LHS, newLHS, newLHS));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Operator getOperator()
  {
    return operator;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setOperator(Operator newOperator)
  {
    Operator oldOperator = operator;
    operator = newOperator == null ? OPERATOR_EDEFAULT : newOperator;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, IMSPackage.COMPOUND_EXPRESSION__OPERATOR, oldOperator, operator));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Expression getRHS()
  {
    return rhs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetRHS(Expression newRHS, NotificationChain msgs)
  {
    Expression oldRHS = rhs;
    rhs = newRHS;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, IMSPackage.COMPOUND_EXPRESSION__RHS, oldRHS, newRHS);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setRHS(Expression newRHS)
  {
    if (newRHS != rhs)
    {
      NotificationChain msgs = null;
      if (rhs != null)
        msgs = ((InternalEObject)rhs).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - IMSPackage.COMPOUND_EXPRESSION__RHS, null, msgs);
      if (newRHS != null)
        msgs = ((InternalEObject)newRHS).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - IMSPackage.COMPOUND_EXPRESSION__RHS, null, msgs);
      msgs = basicSetRHS(newRHS, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, IMSPackage.COMPOUND_EXPRESSION__RHS, newRHS, newRHS));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case IMSPackage.COMPOUND_EXPRESSION__LHS:
        return basicSetLHS(null, msgs);
      case IMSPackage.COMPOUND_EXPRESSION__RHS:
        return basicSetRHS(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case IMSPackage.COMPOUND_EXPRESSION__LHS:
        return getLHS();
      case IMSPackage.COMPOUND_EXPRESSION__OPERATOR:
        return getOperator();
      case IMSPackage.COMPOUND_EXPRESSION__RHS:
        return getRHS();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case IMSPackage.COMPOUND_EXPRESSION__LHS:
        setLHS((Expression)newValue);
        return;
      case IMSPackage.COMPOUND_EXPRESSION__OPERATOR:
        setOperator((Operator)newValue);
        return;
      case IMSPackage.COMPOUND_EXPRESSION__RHS:
        setRHS((Expression)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case IMSPackage.COMPOUND_EXPRESSION__LHS:
        setLHS((Expression)null);
        return;
      case IMSPackage.COMPOUND_EXPRESSION__OPERATOR:
        setOperator(OPERATOR_EDEFAULT);
        return;
      case IMSPackage.COMPOUND_EXPRESSION__RHS:
        setRHS((Expression)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case IMSPackage.COMPOUND_EXPRESSION__LHS:
        return lhs != null;
      case IMSPackage.COMPOUND_EXPRESSION__OPERATOR:
        return operator != OPERATOR_EDEFAULT;
      case IMSPackage.COMPOUND_EXPRESSION__RHS:
        return rhs != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (operator: ");
    result.append(operator);
    result.append(')');
    return result.toString();
  }

} //CompoundExpressionImpl
