/**
 * generated by Xtext 2.34.0
 */
package org.xtext.example.ims.iMS.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.example.ims.iMS.IMSPackage;
import org.xtext.example.ims.iMS.Pump;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Pump</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class PumpImpl extends NumberedElementImpl implements Pump
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected PumpImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return IMSPackage.Literals.PUMP;
  }

} //PumpImpl
