/**
 * generated by Xtext 2.34.0
 */
package org.xtext.example.ims.iMS;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Compound Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.ims.iMS.CompoundExpression#getLHS <em>LHS</em>}</li>
 *   <li>{@link org.xtext.example.ims.iMS.CompoundExpression#getOperator <em>Operator</em>}</li>
 *   <li>{@link org.xtext.example.ims.iMS.CompoundExpression#getRHS <em>RHS</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.ims.iMS.IMSPackage#getCompoundExpression()
 * @model
 * @generated
 */
public interface CompoundExpression extends Expression
{
  /**
   * Returns the value of the '<em><b>LHS</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>LHS</em>' containment reference.
   * @see #setLHS(Expression)
   * @see org.xtext.example.ims.iMS.IMSPackage#getCompoundExpression_LHS()
   * @model containment="true"
   * @generated
   */
  Expression getLHS();

  /**
   * Sets the value of the '{@link org.xtext.example.ims.iMS.CompoundExpression#getLHS <em>LHS</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>LHS</em>' containment reference.
   * @see #getLHS()
   * @generated
   */
  void setLHS(Expression value);

  /**
   * Returns the value of the '<em><b>Operator</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.example.ims.iMS.Operator}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Operator</em>' attribute.
   * @see org.xtext.example.ims.iMS.Operator
   * @see #setOperator(Operator)
   * @see org.xtext.example.ims.iMS.IMSPackage#getCompoundExpression_Operator()
   * @model
   * @generated
   */
  Operator getOperator();

  /**
   * Sets the value of the '{@link org.xtext.example.ims.iMS.CompoundExpression#getOperator <em>Operator</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Operator</em>' attribute.
   * @see org.xtext.example.ims.iMS.Operator
   * @see #getOperator()
   * @generated
   */
  void setOperator(Operator value);

  /**
   * Returns the value of the '<em><b>RHS</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>RHS</em>' containment reference.
   * @see #setRHS(Expression)
   * @see org.xtext.example.ims.iMS.IMSPackage#getCompoundExpression_RHS()
   * @model containment="true"
   * @generated
   */
  Expression getRHS();

  /**
   * Sets the value of the '{@link org.xtext.example.ims.iMS.CompoundExpression#getRHS <em>RHS</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>RHS</em>' containment reference.
   * @see #getRHS()
   * @generated
   */
  void setRHS(Expression value);

} // CompoundExpression
