/**
 * generated by Xtext 2.34.0
 */
package org.xtext.example.ims.iMS;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>IMS</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.ims.iMS.IMS#getIrrigationRules <em>Irrigation Rules</em>}</li>
 *   <li>{@link org.xtext.example.ims.iMS.IMS#getExpressions <em>Expressions</em>}</li>
 *   <li>{@link org.xtext.example.ims.iMS.IMS#getFields <em>Fields</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.ims.iMS.IMSPackage#getIMS()
 * @model
 * @generated
 */
public interface IMS extends EObject
{
  /**
   * Returns the value of the '<em><b>Irrigation Rules</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.ims.iMS.IrrigationRule}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Irrigation Rules</em>' containment reference list.
   * @see org.xtext.example.ims.iMS.IMSPackage#getIMS_IrrigationRules()
   * @model containment="true"
   * @generated
   */
  EList<IrrigationRule> getIrrigationRules();

  /**
   * Returns the value of the '<em><b>Expressions</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.ims.iMS.Expression}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expressions</em>' containment reference list.
   * @see org.xtext.example.ims.iMS.IMSPackage#getIMS_Expressions()
   * @model containment="true"
   * @generated
   */
  EList<Expression> getExpressions();

  /**
   * Returns the value of the '<em><b>Fields</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.ims.iMS.Field}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Fields</em>' containment reference list.
   * @see org.xtext.example.ims.iMS.IMSPackage#getIMS_Fields()
   * @model containment="true"
   * @generated
   */
  EList<Field> getFields();

} // IMS
