/**
 * generated by Xtext 2.34.0
 */
package org.xtext.example.ims.iMS;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.ims.iMS.IMSFactory
 * @model kind="package"
 * @generated
 */
public interface IMSPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "iMS";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/ims/IMS";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "iMS";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  IMSPackage eINSTANCE = org.xtext.example.ims.iMS.impl.IMSPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.ims.iMS.impl.IMSImpl <em>IMS</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.ims.iMS.impl.IMSImpl
   * @see org.xtext.example.ims.iMS.impl.IMSPackageImpl#getIMS()
   * @generated
   */
  int IMS = 0;

  /**
   * The feature id for the '<em><b>Fields</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMS__FIELDS = 0;

  /**
   * The feature id for the '<em><b>Irrigation Rules</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMS__IRRIGATION_RULES = 1;

  /**
   * The feature id for the '<em><b>Expressions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMS__EXPRESSIONS = 2;

  /**
   * The number of structural features of the '<em>IMS</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMS_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.example.ims.iMS.impl.IrrigationRuleImpl <em>Irrigation Rule</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.ims.iMS.impl.IrrigationRuleImpl
   * @see org.xtext.example.ims.iMS.impl.IMSPackageImpl#getIrrigationRule()
   * @generated
   */
  int IRRIGATION_RULE = 1;

  /**
   * The feature id for the '<em><b>Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IRRIGATION_RULE__EXPRESSION = 0;

  /**
   * The feature id for the '<em><b>Setting</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IRRIGATION_RULE__SETTING = 1;

  /**
   * The feature id for the '<em><b>Pumps</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IRRIGATION_RULE__PUMPS = 2;

  /**
   * The feature id for the '<em><b>Duration</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IRRIGATION_RULE__DURATION = 3;

  /**
   * The number of structural features of the '<em>Irrigation Rule</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IRRIGATION_RULE_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.xtext.example.ims.iMS.impl.ExpressionImpl <em>Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.ims.iMS.impl.ExpressionImpl
   * @see org.xtext.example.ims.iMS.impl.IMSPackageImpl#getExpression()
   * @generated
   */
  int EXPRESSION = 2;

  /**
   * The number of structural features of the '<em>Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.example.ims.iMS.impl.NumberedElementImpl <em>Numbered Element</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.ims.iMS.impl.NumberedElementImpl
   * @see org.xtext.example.ims.iMS.impl.IMSPackageImpl#getNumberedElement()
   * @generated
   */
  int NUMBERED_ELEMENT = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NUMBERED_ELEMENT__NAME = 0;

  /**
   * The number of structural features of the '<em>Numbered Element</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NUMBERED_ELEMENT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.ims.iMS.impl.FieldImpl <em>Field</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.ims.iMS.impl.FieldImpl
   * @see org.xtext.example.ims.iMS.impl.IMSPackageImpl#getField()
   * @generated
   */
  int FIELD = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FIELD__NAME = NUMBERED_ELEMENT__NAME;

  /**
   * The feature id for the '<em><b>Sections</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FIELD__SECTIONS = NUMBERED_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Field</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FIELD_FEATURE_COUNT = NUMBERED_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.ims.iMS.impl.SectionImpl <em>Section</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.ims.iMS.impl.SectionImpl
   * @see org.xtext.example.ims.iMS.impl.IMSPackageImpl#getSection()
   * @generated
   */
  int SECTION = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SECTION__NAME = NUMBERED_ELEMENT__NAME;

  /**
   * The feature id for the '<em><b>Pumps</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SECTION__PUMPS = NUMBERED_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Section</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SECTION_FEATURE_COUNT = NUMBERED_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.ims.iMS.impl.PumpImpl <em>Pump</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.ims.iMS.impl.PumpImpl
   * @see org.xtext.example.ims.iMS.impl.IMSPackageImpl#getPump()
   * @generated
   */
  int PUMP = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PUMP__NAME = NUMBERED_ELEMENT__NAME;

  /**
   * The number of structural features of the '<em>Pump</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PUMP_FEATURE_COUNT = NUMBERED_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.example.ims.iMS.impl.AtomicExpressionImpl <em>Atomic Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.ims.iMS.impl.AtomicExpressionImpl
   * @see org.xtext.example.ims.iMS.impl.IMSPackageImpl#getAtomicExpression()
   * @generated
   */
  int ATOMIC_EXPRESSION = 7;

  /**
   * The feature id for the '<em><b>Forecast Lower Bound</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATOMIC_EXPRESSION__FORECAST_LOWER_BOUND = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Forecast Upper Bound</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATOMIC_EXPRESSION__FORECAST_UPPER_BOUND = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Field</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATOMIC_EXPRESSION__FIELD = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Moisture Lower Bound</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATOMIC_EXPRESSION__MOISTURE_LOWER_BOUND = EXPRESSION_FEATURE_COUNT + 3;

  /**
   * The feature id for the '<em><b>Moisture Upper Bound</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATOMIC_EXPRESSION__MOISTURE_UPPER_BOUND = EXPRESSION_FEATURE_COUNT + 4;

  /**
   * The number of structural features of the '<em>Atomic Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATOMIC_EXPRESSION_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 5;

  /**
   * The meta object id for the '{@link org.xtext.example.ims.iMS.impl.CompoundExpressionImpl <em>Compound Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.ims.iMS.impl.CompoundExpressionImpl
   * @see org.xtext.example.ims.iMS.impl.IMSPackageImpl#getCompoundExpression()
   * @generated
   */
  int COMPOUND_EXPRESSION = 8;

  /**
   * The feature id for the '<em><b>LHS</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPOUND_EXPRESSION__LHS = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Operator</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPOUND_EXPRESSION__OPERATOR = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>RHS</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPOUND_EXPRESSION__RHS = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Compound Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPOUND_EXPRESSION_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link org.xtext.example.ims.iMS.WaterSetting <em>Water Setting</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.ims.iMS.WaterSetting
   * @see org.xtext.example.ims.iMS.impl.IMSPackageImpl#getWaterSetting()
   * @generated
   */
  int WATER_SETTING = 9;

  /**
   * The meta object id for the '{@link org.xtext.example.ims.iMS.Operator <em>Operator</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.ims.iMS.Operator
   * @see org.xtext.example.ims.iMS.impl.IMSPackageImpl#getOperator()
   * @generated
   */
  int OPERATOR = 10;


  /**
   * Returns the meta object for class '{@link org.xtext.example.ims.iMS.IMS <em>IMS</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>IMS</em>'.
   * @see org.xtext.example.ims.iMS.IMS
   * @generated
   */
  EClass getIMS();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.ims.iMS.IMS#getFields <em>Fields</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Fields</em>'.
   * @see org.xtext.example.ims.iMS.IMS#getFields()
   * @see #getIMS()
   * @generated
   */
  EReference getIMS_Fields();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.ims.iMS.IMS#getIrrigationRules <em>Irrigation Rules</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Irrigation Rules</em>'.
   * @see org.xtext.example.ims.iMS.IMS#getIrrigationRules()
   * @see #getIMS()
   * @generated
   */
  EReference getIMS_IrrigationRules();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.ims.iMS.IMS#getExpressions <em>Expressions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Expressions</em>'.
   * @see org.xtext.example.ims.iMS.IMS#getExpressions()
   * @see #getIMS()
   * @generated
   */
  EReference getIMS_Expressions();

  /**
   * Returns the meta object for class '{@link org.xtext.example.ims.iMS.IrrigationRule <em>Irrigation Rule</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Irrigation Rule</em>'.
   * @see org.xtext.example.ims.iMS.IrrigationRule
   * @generated
   */
  EClass getIrrigationRule();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.ims.iMS.IrrigationRule#getExpression <em>Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Expression</em>'.
   * @see org.xtext.example.ims.iMS.IrrigationRule#getExpression()
   * @see #getIrrigationRule()
   * @generated
   */
  EReference getIrrigationRule_Expression();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.ims.iMS.IrrigationRule#getSetting <em>Setting</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Setting</em>'.
   * @see org.xtext.example.ims.iMS.IrrigationRule#getSetting()
   * @see #getIrrigationRule()
   * @generated
   */
  EAttribute getIrrigationRule_Setting();

  /**
   * Returns the meta object for the reference list '{@link org.xtext.example.ims.iMS.IrrigationRule#getPumps <em>Pumps</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Pumps</em>'.
   * @see org.xtext.example.ims.iMS.IrrigationRule#getPumps()
   * @see #getIrrigationRule()
   * @generated
   */
  EReference getIrrigationRule_Pumps();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.ims.iMS.IrrigationRule#getDuration <em>Duration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Duration</em>'.
   * @see org.xtext.example.ims.iMS.IrrigationRule#getDuration()
   * @see #getIrrigationRule()
   * @generated
   */
  EAttribute getIrrigationRule_Duration();

  /**
   * Returns the meta object for class '{@link org.xtext.example.ims.iMS.Expression <em>Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expression</em>'.
   * @see org.xtext.example.ims.iMS.Expression
   * @generated
   */
  EClass getExpression();

  /**
   * Returns the meta object for class '{@link org.xtext.example.ims.iMS.Field <em>Field</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Field</em>'.
   * @see org.xtext.example.ims.iMS.Field
   * @generated
   */
  EClass getField();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.ims.iMS.Field#getSections <em>Sections</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Sections</em>'.
   * @see org.xtext.example.ims.iMS.Field#getSections()
   * @see #getField()
   * @generated
   */
  EReference getField_Sections();

  /**
   * Returns the meta object for class '{@link org.xtext.example.ims.iMS.NumberedElement <em>Numbered Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Numbered Element</em>'.
   * @see org.xtext.example.ims.iMS.NumberedElement
   * @generated
   */
  EClass getNumberedElement();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.ims.iMS.NumberedElement#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.ims.iMS.NumberedElement#getName()
   * @see #getNumberedElement()
   * @generated
   */
  EAttribute getNumberedElement_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.example.ims.iMS.Section <em>Section</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Section</em>'.
   * @see org.xtext.example.ims.iMS.Section
   * @generated
   */
  EClass getSection();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.ims.iMS.Section#getPumps <em>Pumps</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Pumps</em>'.
   * @see org.xtext.example.ims.iMS.Section#getPumps()
   * @see #getSection()
   * @generated
   */
  EReference getSection_Pumps();

  /**
   * Returns the meta object for class '{@link org.xtext.example.ims.iMS.Pump <em>Pump</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Pump</em>'.
   * @see org.xtext.example.ims.iMS.Pump
   * @generated
   */
  EClass getPump();

  /**
   * Returns the meta object for class '{@link org.xtext.example.ims.iMS.AtomicExpression <em>Atomic Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Atomic Expression</em>'.
   * @see org.xtext.example.ims.iMS.AtomicExpression
   * @generated
   */
  EClass getAtomicExpression();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.ims.iMS.AtomicExpression#getForecastLowerBound <em>Forecast Lower Bound</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Forecast Lower Bound</em>'.
   * @see org.xtext.example.ims.iMS.AtomicExpression#getForecastLowerBound()
   * @see #getAtomicExpression()
   * @generated
   */
  EAttribute getAtomicExpression_ForecastLowerBound();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.ims.iMS.AtomicExpression#getForecastUpperBound <em>Forecast Upper Bound</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Forecast Upper Bound</em>'.
   * @see org.xtext.example.ims.iMS.AtomicExpression#getForecastUpperBound()
   * @see #getAtomicExpression()
   * @generated
   */
  EAttribute getAtomicExpression_ForecastUpperBound();

  /**
   * Returns the meta object for the reference '{@link org.xtext.example.ims.iMS.AtomicExpression#getField <em>Field</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Field</em>'.
   * @see org.xtext.example.ims.iMS.AtomicExpression#getField()
   * @see #getAtomicExpression()
   * @generated
   */
  EReference getAtomicExpression_Field();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.ims.iMS.AtomicExpression#getMoistureLowerBound <em>Moisture Lower Bound</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Moisture Lower Bound</em>'.
   * @see org.xtext.example.ims.iMS.AtomicExpression#getMoistureLowerBound()
   * @see #getAtomicExpression()
   * @generated
   */
  EAttribute getAtomicExpression_MoistureLowerBound();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.ims.iMS.AtomicExpression#getMoistureUpperBound <em>Moisture Upper Bound</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Moisture Upper Bound</em>'.
   * @see org.xtext.example.ims.iMS.AtomicExpression#getMoistureUpperBound()
   * @see #getAtomicExpression()
   * @generated
   */
  EAttribute getAtomicExpression_MoistureUpperBound();

  /**
   * Returns the meta object for class '{@link org.xtext.example.ims.iMS.CompoundExpression <em>Compound Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Compound Expression</em>'.
   * @see org.xtext.example.ims.iMS.CompoundExpression
   * @generated
   */
  EClass getCompoundExpression();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.ims.iMS.CompoundExpression#getLHS <em>LHS</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>LHS</em>'.
   * @see org.xtext.example.ims.iMS.CompoundExpression#getLHS()
   * @see #getCompoundExpression()
   * @generated
   */
  EReference getCompoundExpression_LHS();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.ims.iMS.CompoundExpression#getOperator <em>Operator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Operator</em>'.
   * @see org.xtext.example.ims.iMS.CompoundExpression#getOperator()
   * @see #getCompoundExpression()
   * @generated
   */
  EAttribute getCompoundExpression_Operator();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.ims.iMS.CompoundExpression#getRHS <em>RHS</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>RHS</em>'.
   * @see org.xtext.example.ims.iMS.CompoundExpression#getRHS()
   * @see #getCompoundExpression()
   * @generated
   */
  EReference getCompoundExpression_RHS();

  /**
   * Returns the meta object for enum '{@link org.xtext.example.ims.iMS.WaterSetting <em>Water Setting</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Water Setting</em>'.
   * @see org.xtext.example.ims.iMS.WaterSetting
   * @generated
   */
  EEnum getWaterSetting();

  /**
   * Returns the meta object for enum '{@link org.xtext.example.ims.iMS.Operator <em>Operator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Operator</em>'.
   * @see org.xtext.example.ims.iMS.Operator
   * @generated
   */
  EEnum getOperator();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  IMSFactory getIMSFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.ims.iMS.impl.IMSImpl <em>IMS</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.ims.iMS.impl.IMSImpl
     * @see org.xtext.example.ims.iMS.impl.IMSPackageImpl#getIMS()
     * @generated
     */
    EClass IMS = eINSTANCE.getIMS();

    /**
     * The meta object literal for the '<em><b>Fields</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference IMS__FIELDS = eINSTANCE.getIMS_Fields();

    /**
     * The meta object literal for the '<em><b>Irrigation Rules</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference IMS__IRRIGATION_RULES = eINSTANCE.getIMS_IrrigationRules();

    /**
     * The meta object literal for the '<em><b>Expressions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference IMS__EXPRESSIONS = eINSTANCE.getIMS_Expressions();

    /**
     * The meta object literal for the '{@link org.xtext.example.ims.iMS.impl.IrrigationRuleImpl <em>Irrigation Rule</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.ims.iMS.impl.IrrigationRuleImpl
     * @see org.xtext.example.ims.iMS.impl.IMSPackageImpl#getIrrigationRule()
     * @generated
     */
    EClass IRRIGATION_RULE = eINSTANCE.getIrrigationRule();

    /**
     * The meta object literal for the '<em><b>Expression</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference IRRIGATION_RULE__EXPRESSION = eINSTANCE.getIrrigationRule_Expression();

    /**
     * The meta object literal for the '<em><b>Setting</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute IRRIGATION_RULE__SETTING = eINSTANCE.getIrrigationRule_Setting();

    /**
     * The meta object literal for the '<em><b>Pumps</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference IRRIGATION_RULE__PUMPS = eINSTANCE.getIrrigationRule_Pumps();

    /**
     * The meta object literal for the '<em><b>Duration</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute IRRIGATION_RULE__DURATION = eINSTANCE.getIrrigationRule_Duration();

    /**
     * The meta object literal for the '{@link org.xtext.example.ims.iMS.impl.ExpressionImpl <em>Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.ims.iMS.impl.ExpressionImpl
     * @see org.xtext.example.ims.iMS.impl.IMSPackageImpl#getExpression()
     * @generated
     */
    EClass EXPRESSION = eINSTANCE.getExpression();

    /**
     * The meta object literal for the '{@link org.xtext.example.ims.iMS.impl.FieldImpl <em>Field</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.ims.iMS.impl.FieldImpl
     * @see org.xtext.example.ims.iMS.impl.IMSPackageImpl#getField()
     * @generated
     */
    EClass FIELD = eINSTANCE.getField();

    /**
     * The meta object literal for the '<em><b>Sections</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FIELD__SECTIONS = eINSTANCE.getField_Sections();

    /**
     * The meta object literal for the '{@link org.xtext.example.ims.iMS.impl.NumberedElementImpl <em>Numbered Element</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.ims.iMS.impl.NumberedElementImpl
     * @see org.xtext.example.ims.iMS.impl.IMSPackageImpl#getNumberedElement()
     * @generated
     */
    EClass NUMBERED_ELEMENT = eINSTANCE.getNumberedElement();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NUMBERED_ELEMENT__NAME = eINSTANCE.getNumberedElement_Name();

    /**
     * The meta object literal for the '{@link org.xtext.example.ims.iMS.impl.SectionImpl <em>Section</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.ims.iMS.impl.SectionImpl
     * @see org.xtext.example.ims.iMS.impl.IMSPackageImpl#getSection()
     * @generated
     */
    EClass SECTION = eINSTANCE.getSection();

    /**
     * The meta object literal for the '<em><b>Pumps</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SECTION__PUMPS = eINSTANCE.getSection_Pumps();

    /**
     * The meta object literal for the '{@link org.xtext.example.ims.iMS.impl.PumpImpl <em>Pump</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.ims.iMS.impl.PumpImpl
     * @see org.xtext.example.ims.iMS.impl.IMSPackageImpl#getPump()
     * @generated
     */
    EClass PUMP = eINSTANCE.getPump();

    /**
     * The meta object literal for the '{@link org.xtext.example.ims.iMS.impl.AtomicExpressionImpl <em>Atomic Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.ims.iMS.impl.AtomicExpressionImpl
     * @see org.xtext.example.ims.iMS.impl.IMSPackageImpl#getAtomicExpression()
     * @generated
     */
    EClass ATOMIC_EXPRESSION = eINSTANCE.getAtomicExpression();

    /**
     * The meta object literal for the '<em><b>Forecast Lower Bound</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ATOMIC_EXPRESSION__FORECAST_LOWER_BOUND = eINSTANCE.getAtomicExpression_ForecastLowerBound();

    /**
     * The meta object literal for the '<em><b>Forecast Upper Bound</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ATOMIC_EXPRESSION__FORECAST_UPPER_BOUND = eINSTANCE.getAtomicExpression_ForecastUpperBound();

    /**
     * The meta object literal for the '<em><b>Field</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ATOMIC_EXPRESSION__FIELD = eINSTANCE.getAtomicExpression_Field();

    /**
     * The meta object literal for the '<em><b>Moisture Lower Bound</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ATOMIC_EXPRESSION__MOISTURE_LOWER_BOUND = eINSTANCE.getAtomicExpression_MoistureLowerBound();

    /**
     * The meta object literal for the '<em><b>Moisture Upper Bound</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ATOMIC_EXPRESSION__MOISTURE_UPPER_BOUND = eINSTANCE.getAtomicExpression_MoistureUpperBound();

    /**
     * The meta object literal for the '{@link org.xtext.example.ims.iMS.impl.CompoundExpressionImpl <em>Compound Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.ims.iMS.impl.CompoundExpressionImpl
     * @see org.xtext.example.ims.iMS.impl.IMSPackageImpl#getCompoundExpression()
     * @generated
     */
    EClass COMPOUND_EXPRESSION = eINSTANCE.getCompoundExpression();

    /**
     * The meta object literal for the '<em><b>LHS</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMPOUND_EXPRESSION__LHS = eINSTANCE.getCompoundExpression_LHS();

    /**
     * The meta object literal for the '<em><b>Operator</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COMPOUND_EXPRESSION__OPERATOR = eINSTANCE.getCompoundExpression_Operator();

    /**
     * The meta object literal for the '<em><b>RHS</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMPOUND_EXPRESSION__RHS = eINSTANCE.getCompoundExpression_RHS();

    /**
     * The meta object literal for the '{@link org.xtext.example.ims.iMS.WaterSetting <em>Water Setting</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.ims.iMS.WaterSetting
     * @see org.xtext.example.ims.iMS.impl.IMSPackageImpl#getWaterSetting()
     * @generated
     */
    EEnum WATER_SETTING = eINSTANCE.getWaterSetting();

    /**
     * The meta object literal for the '{@link org.xtext.example.ims.iMS.Operator <em>Operator</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.ims.iMS.Operator
     * @see org.xtext.example.ims.iMS.impl.IMSPackageImpl#getOperator()
     * @generated
     */
    EEnum OPERATOR = eINSTANCE.getOperator();

  }

} //IMSPackage
