/**
 * generated by Xtext 2.34.0
 */
package org.xtext.example.ims.iMS;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Irrigation Rule</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.ims.iMS.IrrigationRule#getExpression <em>Expression</em>}</li>
 *   <li>{@link org.xtext.example.ims.iMS.IrrigationRule#getSetting <em>Setting</em>}</li>
 *   <li>{@link org.xtext.example.ims.iMS.IrrigationRule#getPumps <em>Pumps</em>}</li>
 *   <li>{@link org.xtext.example.ims.iMS.IrrigationRule#getDuration <em>Duration</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.ims.iMS.IMSPackage#getIrrigationRule()
 * @model
 * @generated
 */
public interface IrrigationRule extends EObject
{
  /**
   * Returns the value of the '<em><b>Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expression</em>' containment reference.
   * @see #setExpression(Expression)
   * @see org.xtext.example.ims.iMS.IMSPackage#getIrrigationRule_Expression()
   * @model containment="true"
   * @generated
   */
  Expression getExpression();

  /**
   * Sets the value of the '{@link org.xtext.example.ims.iMS.IrrigationRule#getExpression <em>Expression</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Expression</em>' containment reference.
   * @see #getExpression()
   * @generated
   */
  void setExpression(Expression value);

  /**
   * Returns the value of the '<em><b>Setting</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.example.ims.iMS.WaterSetting}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Setting</em>' attribute.
   * @see org.xtext.example.ims.iMS.WaterSetting
   * @see #setSetting(WaterSetting)
   * @see org.xtext.example.ims.iMS.IMSPackage#getIrrigationRule_Setting()
   * @model
   * @generated
   */
  WaterSetting getSetting();

  /**
   * Sets the value of the '{@link org.xtext.example.ims.iMS.IrrigationRule#getSetting <em>Setting</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Setting</em>' attribute.
   * @see org.xtext.example.ims.iMS.WaterSetting
   * @see #getSetting()
   * @generated
   */
  void setSetting(WaterSetting value);

  /**
   * Returns the value of the '<em><b>Pumps</b></em>' reference list.
   * The list contents are of type {@link org.xtext.example.ims.iMS.Pump}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pumps</em>' reference list.
   * @see org.xtext.example.ims.iMS.IMSPackage#getIrrigationRule_Pumps()
   * @model
   * @generated
   */
  EList<Pump> getPumps();

  /**
   * Returns the value of the '<em><b>Duration</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Duration</em>' attribute.
   * @see #setDuration(int)
   * @see org.xtext.example.ims.iMS.IMSPackage#getIrrigationRule_Duration()
   * @model
   * @generated
   */
  int getDuration();

  /**
   * Sets the value of the '{@link org.xtext.example.ims.iMS.IrrigationRule#getDuration <em>Duration</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Duration</em>' attribute.
   * @see #getDuration()
   * @generated
   */
  void setDuration(int value);

} // IrrigationRule
