/**
 * generated by Xtext 2.34.0
 */
package org.xtext.example.ims.iMS;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Numbered Element</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.ims.iMS.NumberedElement#getAssetNumber <em>Asset Number</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.ims.iMS.IMSPackage#getNumberedElement()
 * @model
 * @generated
 */
public interface NumberedElement extends EObject
{
  /**
   * Returns the value of the '<em><b>Asset Number</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Asset Number</em>' attribute.
   * @see #setAssetNumber(String)
   * @see org.xtext.example.ims.iMS.IMSPackage#getNumberedElement_AssetNumber()
   * @model
   * @generated
   */
  String getAssetNumber();

  /**
   * Sets the value of the '{@link org.xtext.example.ims.iMS.NumberedElement#getAssetNumber <em>Asset Number</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Asset Number</em>' attribute.
   * @see #getAssetNumber()
   * @generated
   */
  void setAssetNumber(String value);

} // NumberedElement
