/**
 * generated by Xtext 2.34.0
 */
package org.xtext.example.ims.iMS;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Pump</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.ims.iMS.IMSPackage#getPump()
 * @model
 * @generated
 */
public interface Pump extends NumberedElement
{
} // Pump
