/**
 * generated by Xtext 2.34.0
 */
package org.xtext.example.ims.iMS;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Section</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.ims.iMS.Section#getPumps <em>Pumps</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.ims.iMS.IMSPackage#getSection()
 * @model
 * @generated
 */
public interface Section extends NumberedElement
{
  /**
   * Returns the value of the '<em><b>Pumps</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.ims.iMS.Pump}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pumps</em>' containment reference list.
   * @see org.xtext.example.ims.iMS.IMSPackage#getSection_Pumps()
   * @model containment="true"
   * @generated
   */
  EList<Pump> getPumps();

} // Section
