/*
 * generated by Xtext 2.34.0
 */
package org.xtext.example.ims.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractIMSScopeProvider extends DelegatingScopeProvider {
}
