/*
 * generated by Xtext 2.34.0
 */
package org.xtext.example.ims.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.example.ims.parser.antlr.internal.InternalIMSParser;
import org.xtext.example.ims.services.IMSGrammarAccess;

public class IMSParser extends AbstractAntlrParser {

	@Inject
	private IMSGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalIMSParser createParser(XtextTokenStream stream) {
		return new InternalIMSParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "IMS";
	}

	public IMSGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(IMSGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
