/*
 * generated by Xtext 2.34.0
 */
package org.xtext.example.ims.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class IMSUiModule extends AbstractIMSUiModule {

	public IMSUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
